# Generated by Django 5.2.5 on 2025-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Number of Days')),
                ('night', models.IntegerField(default=0, help_text='Number of Nights')),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
